# action.yaml
name: 'Get LemonTreeAutomation'
description: 'This action downloads LieberLieber LemonTree.Automation for Sparx Systems Enterprise Architect on a build runner!'
inputs:
  License:
    description: 'A string containing the license information'
    required: false
    default: ''
outputs:
  LemonTreeAutomationExecutable:
    description: 'Path to the Executable'
    value: "${{steps.DownloadLTA.outputs.LemonTreeAutomationExecutable}}"
runs:
  using: 'composite'
  steps:
    - id: DownloadLTA
      run: "& $env:GITHUB_ACTION_PATH/getLTA.ps1 -RunnerOs '${{runner.os}}'-License '${{inputs.License}}'"
      shell: pwsh
