# Copyright (c) LieberLieber Software GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Ubuntu  Test

on:
 push:

env:
  ModelName: model
  ModelExtension: qeax

jobs:
  ConsistencyCheck:
    defaults:
      run:
        shell: pwsh
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      

      - name: GetLTA
        uses: ./
        id: GetLTA
        with:
          License: ${{secrets.LTALICENSE}}
      #Consitentcy Check is the most easy LemonTree.Automation operation for more advanced uses including diff and merge look at https://github.com/LieberLieber/LemonTree.Automation.Workflows
      - name: ConsistencyCheck
        run: |
            &"${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}" ConsistencyCheck --Model ${{env.ModelName}}.${{env.ModelExtension}}